export default function(){
    return [
        {
            ticketsid: 1,
            subject: 'Test Ticket 1',
            description: 'Test Ticket Description',
            status: 'Active',
            StartDate: new Date(),
            endDate: new Date(),
            category: 'Software',
        },
        {
            ticketsid: 2,
            subject: 'Test Ticket 2',
            description: 'Test Ticket Description 2',
            status: 'Active',
            StartDate: new Date(),
            endDate: new Date(),
            category: 'Hardware',
        },
        {
            ticketsid: 3,
            subject: 'Test Ticket 3',
            description: 'Test Ticket Description 3',
            status: 'Active',
            StartDate: new Date(),
            endDate: new Date(),
            category: 'Software',
        },
        {
            ticketsid: 4,
            subject: 'Test Ticket 4',
            description: 'Test Ticket Description 4',
            status: 'Active',
            StartDate: new Date(),
            endDate: new Date(),
            category: 'Software',
        },
        {
            ticketsid: 5,
            subject: 'Test Ticket 5',
            description: 'Test Ticket Description 5',
            status: 'Active',
            StartDate: new Date(),
            endDate: new Date(),
            category: 'Software',
        },
        {
            ticketsid: 6,
            subject: 'Test Ticket 6',
            description: 'Test Ticket Description 6',
            status: 'Active',
            StartDate: new Date(),
            endDate: new Date(),
            category: 'Software',
        },
        
        {
            ticketsid: 7,
            subject: 'Test Ticket 7',
            description: 'Test Ticket Description 7',
            status: 'Active',
            StartDate: new Date(),
            endDate: new Date(),
            category: 'Software',
        },
    ]
}